rmcs_executor:
  ros__parameters:
    update_rate: 1000.0

    components:
      - rmcs_core::hardware::DartPitchHardware -> dart_pitch_hardware

      - rmcs_core::controller::DartPitchController -> dart_pitch_controller
      - rmcs_core::controller::pid::PidController -> dart_pitch_left_velocity_pid_controller
      - rmcs_core::controller::pid::PidController -> dart_pitch_right_velocity_pid_controller
      - rmcs_core::broadcaster::ValueBroadcaster -> value_broadcaster

dart_pitch_hardware:
  ros__parameters:
    board_serial: ""

dart_pitch_controller:
  ros__parameters:
    sync_kp: 0.1 
    max_sync_velocity: 2.0
    dart_velocity: 10.0
    threshold: 0.05 #未知具体
    
dart_pitch_left_velocity_pid_controller:
  ros__parameters:
    measurement: /dart/left_motor/velocity
    setpoint: /dart/left_motor/control_velocity
    control: /dart/left_motor/control_torque
    kp: 0.001
    ki: 0.000
    kd: 0.00

    integral_min: -50.0
    integral_max: 50.0

dart_pitch_right_velocity_pid_controller:
  ros__parameters:
    measurement: /dart/right_motor/velocity
    setpoint: /dart/right_motor/control_velocity
    control: /dart/right_motor/control_torque
    kp: 0.001
    ki: 0.0
    kd: 0.0

    integral_min: -50.0
    integral_max: 50.0